CREATE TABLE Person (
	personId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(100) UNIQUE NOT NULL,
	yearOfBirth int
);

CREATE TABLE Book (
	bookId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	personId int REFERENCES Person (personId) ON DELETE CASCADE,
	title varchar(100) NOT NULL UNIQUE,
	author varchar(100) NOT NULL UNIQUE,
	yearOfWriting int
);

INSERT INTO Person (name, yearOfBirth) VALUES ('Миронов Александр Иванович', 1975);
INSERT INTO Person (name, yearOfBirth) VALUES ('Порфирьев Алексей Васильевич', 1990);
INSERT INTO Person (name, yearOfBirth) VALUES ('Никитин Игорь Владимирович', 1999);
INSERT INTO Person (name, yearOfBirth) VALUES ('Деменьтев Глеб Олегович', 1977);


INSERT INTO Book (title, author, yearOfWriting) VALUES ('Как закалялась сталь', 'Николай Островский', 1934);
INSERT INTO Book (title, author, yearOfWriting) VALUES ('Архипелаг ГУЛАГ', 'Александр Солженицын', 1968);
INSERT INTO Book (title, author, yearOfWriting) VALUES ('Война и мир', 'Лев Толстой', 1869);
INSERT INTO Book (title, author, yearOfWriting) VALUES ('Дом с мезонином', 'Антон Чехов', 1896);


