CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL UNIQUE,
    year_of_birth int NOT NULL
);

CREATE TABLE Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL,
    taken_at timestamp,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
);

INSERT INTO Person (full_name, year_of_birth) VALUES ('Миронов Александр Иванович', 1975);
INSERT INTO Person (full_name, year_of_birth) VALUES ('Порфирьев Алексей Васильевич', 1990);
INSERT INTO Person (full_name, year_of_birth) VALUES ('Никитин Игорь Владимирович', 1999);
INSERT INTO Person (full_name, year_of_birth) VALUES ('Деменьтев Глеб Олегович', 1977);


INSERT INTO Book (title, author, year) VALUES ('Как закалялась сталь', 'Николай Островский', 1934);
INSERT INTO Book (title, author, year) VALUES ('Архипелаг ГУЛАГ', 'Александр Солженицын', 1968);
INSERT INTO Book (title, author, year) VALUES ('Война и мир', 'Лев Толстой', 1869);
INSERT INTO Book (title, author, year) VALUES ('Дом с мезонином', 'Антон Чехов', 1896);

